# Meta
title: "EpicBounties"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Plugins
plugins:
  - jekyll-feed

# Feed
feed:
  categories:
    - en
    - es

# Default scopes and values
defaults:
  -
    scope:
      path: "en/"
    values:
      language: "en"
  -
    scope:
      path: "es/"
    values:
      language: "es"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/en/"
    values:
      language: "en"
      categories: "en"
  -
    scope:
      path: "_posts/es/"
    values:
      language: "es"
      categories: "es"

# Pagination
paginate: 12
paginate_path: "/archive/page:num/"

# Exclude from processing
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
