# Meta
title:
  en: "EpicBounties - The Final Bug Bounty Platform"
  es: "EpicBounties - La Plataforma de Bug Bounty de Habla Hispana"
description:
  en: "Epic Bounties helps companies reduce security risks by working with the best community of ethical hackers"
  es: "Epic Bounties ayuda a las empresas a reducir los riesgos de seguridad trabajando con la mejor comunidad de hackers éticos hispanohablante"

baseurl: ""
# dev
url: ""
# production
#url: "https://www.epicbounties.com"
# redirect 404 to home
redirect-not-found: false

# Integrations
mailchimp: "" # put here mailchimp action url

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

gems:
  - jekyll-paginate-v2

# collections:
#   en:
#     output: true
#     permalink: /posts/en/:path/
#   es:
#     output: true
#     permalink: /posts/es/:path/

permalink: pretty

  ############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 22

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################





# Feed
feed:
  categories:
    - en
    - es

# GH-PAGES do not support front matter defaults
# Default scopes and values
# defaults:
#   -
#     scope:
#       path: "en/"
#     values:
#       language: "en"
#   -
#     scope:
#       path: "es/"
#     value:
#       language: "es"
#   -
#     scope:
#       path: "_posts"
#     values:
#       layout: "post"
#   -
#     scope:
#       path: "_posts/en/"
#     values:
#       language: "en"
#       categories: "en"
#   -
#     scope:
#       path: "_posts/es/"
#     values:
#       language: "es"
#       categories: "es"

# Pagination
#paginate: 12
#paginate_path: "/archive/page:num/"

# Exclude from processing
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

permalink: /:categories/:title.html
