# Meta
title:
  en: "EpicBounties - La Plataforma de Bug Bounty de Habla Hispana"
  es: "EpicBounties - The Final Bug Bounty Platform"
description:
  en: "Epic Bounties helps companies reduce security risks by working with the best community of ethical hackers"
  es: "Epic Bounties ayuda a las empresas a reducir los riesgos de seguridad trabajando con la mejor comunidad de hackers éticos hispanohablante"

baseurl: ""
# dev
url: ""
# production
#url: "https://www.epicbounties.com"
# redirect 404 to home
redirect-not-found: false

# Integrations
mailchimp: "" # put here mailchimp action url

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Feed
feed:
  categories:
    - en
    - es

# GH-PAGES do not support front matter defaults
# Default scopes and values
# defaults:
#   -
#     scope:
#       path: "en/"
#     values:
#       language: "en"
#   -
#     scope:
#       path: "es/"
#     value:
#       language: "es"
#   -
#     scope:
#       path: "_posts"
#     values:
#       layout: "post"
#   -
#     scope:
#       path: "_posts/en/"
#     values:
#       language: "en"
#       categories: "en"
#   -
#     scope:
#       path: "_posts/es/"
#     values:
#       language: "es"
#       categories: "es"

# Pagination
paginate: 12
paginate_path: "/archive/page:num/"

# Exclude from processing
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

permalink: /:categories/:title.html
